- name: configure backend server
  hosts: backend
  become: yes
  tasks:
  - name: disable dnf nodejs
    ansible.builtin.command: dnf module disable nodejs -y
  - name: enable dnf nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y
  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  - name: create expende user # user add Expense
    ansible.builtin.user:
      name: expense